---

- hosts: home:office
  sudo: yes
  tasks:
      - name: install_pre
        yum: name={{ item }} state=latest
        with_items:
            - httpd
            - tar
            - wget
        tags: install_pre
      - name: install_kibana
        shell: cd /var/www/html && wget https://download.elasticsearch.org/kibana/kibana/kibana-3.1.0.tar.gz && tar xvf kibana-3.1.0.tar.gz && ln -s kibana-3.1.0 kibana
        tags: install
      - name: service_httpd
        service: name={{ item }}  state=started enabled=yes
        with_items:
            - httpd
        tags: service
